Repository olmps/memo, pull requests merged in 2021-04, with the labels that each got.

#22 Adds Sprint 3 (ptBR) doc
  .process/sprints_ptBR/03_Sprint.pdf
Labels: documentation

#19 Architecture updates
  .resources/00arch_overview.png
  .resources/00arch_overview_simple.png
  .resources/01arch_overview_complex.png
  ARCHITECTURE.md
  CHANGELOG.md
  lib/application/view-models/app_vm.dart
  lib/data/database_repository.dart
  lib/data/gateways/document_database_gateway.dart
  lib/data/gateways/sembast_database.dart
  lib/data/repositories/deck_repository.dart
  lib/data/serializers/card_block_serializer.dart
  lib/data/serializers/card_execution_serializer.dart
  lib/data/serializers/card_serializer.dart
  lib/data/serializers/deck_serializer.dart
  lib/data/serializers/resource_serializer.dart
  lib/data/serializers/serializer.dart
  lib/domain/models/card.dart
  lib/domain/models/card_execution.dart
  lib/domain/models/deck.dart
  lib/domain/models/resource.dart
  lib/domain/services/.gitkeep
  lib/domain/services/deck_services.dart
  pubspec.yaml
  test/data/database_repository_test.dart
  test/data/serializers/card_block_serializer_test.dart
  test/data/serializers/card_execution_serializer_test.dart
  test/data/serializers/card_serializer_test.dart
  test/data/serializers/deck_serializer_test.dart
  test/data/serializers/resource_serializer_test.dart
Labels: architecture

#23 Update README.md
  README.md
Labels: documentation

#18 Add github actions workflow
  .github/workflows/flutter-ci.yml
Labels: toolkit

#28 Add CodeCov to Github Actions Workflow #26
  .github/workflows/flutter-ci.yml
  README.md
  README_ptbr.md
  lib/application/coordinator/routes_coordinator.dart
  pubspec.lock
  pubspec.yaml
Labels: toolkit

#32 Base theme components
  ARCHITECTURE.md
  assets/fonts/RobotoMono-Bold.ttf
  assets/fonts/RobotoMono-ExtraLight.ttf
  assets/fonts/RobotoMono-LICENSE.txt
  assets/fonts/RobotoMono-Light.ttf
  assets/fonts/RobotoMono-Medium.ttf
  assets/fonts/RobotoMono-Regular.ttf
  assets/fonts/RobotoMono-SemiBold.ttf
  assets/fonts/RobotoMono-Thin.ttf
  assets/images/icons/2.0x/chevron_left.png
  assets/images/icons/2.0x/chevron_right.png
  assets/images/icons/2.0x/close.png
  assets/images/icons/2.0x/folder.png
  assets/images/icons/2.0x/link.png
  assets/images/icons/2.0x/settings.png
  assets/images/icons/2.0x/trending_up_arrow.png
  assets/images/icons/3.0x/chevron_left.png
  assets/images/icons/3.0x/chevron_right.png
  assets/images/icons/3.0x/close.png
  assets/images/icons/3.0x/folder.png
  assets/images/icons/3.0x/link.png
  assets/images/icons/3.0x/settings.png
  assets/images/icons/3.0x/trending_up_arrow.png
  assets/images/icons/chevron_left.png
  assets/images/icons/chevron_right.png
  assets/images/icons/close.png
  assets/images/icons/folder.png
  assets/images/icons/link.png
  assets/images/icons/settings.png
  lib/application/constants/images.dart
  lib/application/constants/spacings.dart
  lib/application/utils/.gitkeep
  lib/application/utils/license_update.dart
  lib/main.dart
  pubspec.yaml
Labels: architecture

#33 Adds ThemeController
  lib/application/app.dart
  lib/application/constants/.gitkeep
  lib/application/constants/dimensions.dart
  lib/application/coordinator/routes_coordinator.dart
  lib/application/layout_provider.dart
  lib/application/theme/material_theme_data.dart
  lib/application/theme/memo_theme_colors.dart
  lib/application/theme/memo_theme_data.dart
  lib/application/theme/theme_controller.dart
  test/application/theme/theme_controller_test.dart
  test/utils/.gitkeep
  test/utils/widget_pump.dart
Labels: architecture

#34 Adds TextTag, PrimaryTextTag and SecondaryTextTag widgets
  lib/application/widgets/.gitkeep
  lib/application/widgets/text_tag.dart
  lib/application/widgets/theme/themed_text_tag.dart
Labels: architecture

#35 Adds AssetIconButton material widget
  lib/application/widgets/material/asset_icon_button.dart
Labels: architecture

#36 Adds DecoratedTabBar material widget
  lib/application/widgets/material/decorated_tab_bar.dart
  test/application/widgets/material/decorated_tab_bar_test.dart
Labels: architecture

#37 Adds SecondaryButton theme widget
  lib/application/widgets/theme/secondary_button.dart
Labels: architecture

#38 Adds AnimatableProgress and AnimatableLinearProgress widgets
  lib/application/widgets/animatable_progress.dart
  test/application/widgets/animatable_progress_test.dart
Labels: architecture

#31 Add test for listenAll method
  test/data/database_repository_test.dart
Labels: enhancement

#40 Adds AnimatableCircularProgress
  lib/application/widgets/animatable_progress.dart
  test/application/widgets/animatable_progress_test.dart
Labels: architecture

#42 Overall tests enhancements
  test/data/database_repository_test.dart
  test/data/serializers/card_execution_serializer_test.dart
  test/domain/models/card_block_test.dart
  test/domain/models/card_execution_test.dart
  test/domain/models/card_test.dart
  test/domain/models/deck_test.dart
  test/domain/models/resource_test.dart
Labels: enhancement

#44 Adds Collections Page
  assets/images/icons/trending_up_arrow.png
  lib/application/app.dart
  lib/application/constants/colors.dart
  lib/application/constants/dimensions.dart
  lib/application/constants/images.dart
  lib/application/constants/strings.dart
  lib/application/coordinator/routes_coordinator.dart
  lib/application/pages/home/collections/collections_list_view.dart
  lib/application/pages/home/collections/collections_page.dart
  lib/application/pages/home/home_page.dart
  lib/application/theme/material_theme_data.dart
  lib/application/theme/memo_theme_colors.dart
  lib/application/theme/theme_controller.dart
  lib/application/view-models/home/collections_vm.dart
  lib/application/widgets/animatable_progress.dart
  lib/application/widgets/material/asset_icon_button.dart
  lib/application/widgets/material/decorated_tab_bar.dart
  lib/application/widgets/theme/secondary_button.dart
  lib/application/widgets/theme/themed_tab_bar.dart
  lib/application/widgets/theme/themed_text_tag.dart
  test/application/theme/theme_controller_test.dart
  test/application/widgets/material/decorated_tab_bar_test.dart
  test/application/widgets/theme/themed_tab_bar_test.dart
Labels: feature

#45 Adds `ProgressPage`
  lib/application/constants/dimensions.dart
  lib/application/constants/strings.dart
  lib/application/pages/home/home_page.dart
  lib/application/pages/home/progress/progress_page.dart
  lib/application/view-models/home/progress_vm.dart
Labels: feature
