Repository olmps/memo, pull requests merged in 2021-08, with the labels that each got.

#171 Redesigned empty state
  assets/images/illustrations/2.0x/folder_big.png
  assets/images/illustrations/3.0x/folder_big.png
  assets/images/illustrations/folder_big.png
  lib/application/constants/dimensions.dart
  lib/application/constants/images.dart
  lib/application/constants/strings.dart
  lib/application/pages/home/collections/collections_page.dart
Labels: enhancement, flutter

#173 Replace `AlertDialog` by `showModalBottomSheet`
  lib/application/constants/strings.dart
  lib/application/pages/execution/collection_execution_page.dart
  lib/application/theme/memo_theme_colors.dart
  lib/application/theme/memo_theme_data.dart
  lib/application/theme/theme_controller.dart
  lib/application/utils/bottom_sheet.dart
  lib/application/widgets/theme/destructive_button.dart
  lib/application/widgets/theme/secondary_button.dart
Labels: enhancement, flutter

#174 Fixes SafeArea in `ExecutionTerminal`
  lib/application/pages/execution/collection_execution_page.dart
Labels: enhancement, flutter

#181 0.2.0 rc.1
  CHANGELOG.md
  pubspec.lock
  pubspec.yaml
Labels: flutter, release

#182 Fixes release workflow
  CHANGELOG.md
  android/fastlane/Fastfile
  ios/fastlane/Fastfile
Labels: bug, toolkit

#185 Animations stutter fix
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  CHANGELOG.md
  android/app/build.gradle
  android/fastlane/Fastfile
  android_animations.json
  ios/Podfile.lock
  ios/fastlane/Fastfile
  ios_animations.json
  lib/application/pages/details/collection_details_page.dart
  lib/application/pages/home/collections/collections_list_view.dart
  lib/application/widgets/theme/collection_card.dart
  lib/application/widgets/theme/item_collection_card.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, UX/UI, flutter

#187 Refactors `ExecutionTerminal` exposing a `TerminalController`
  lib/application/constants/animations.dart
  lib/application/constants/strings.dart
  lib/application/pages/execution/collection_execution_page.dart
  lib/application/pages/execution/execution_terminal.dart
  lib/application/view-models/execution/collection_execution_vm.dart
Labels: bug, enhancement, flutter

#188 Bumps `CHANGELOG` to `0.2.0`
  CHANGELOG.md
Labels: documentation
