Repository olmps/memo, pull requests merged in 2021-07, with the labels that each got.

#114 Fixes Crashlytics access before Firebase is initialized
  lib/main.dart
Labels: bug

#106 Collection card hero fix
  lib/application/widgets/theme/hero_collection_card.dart
Labels: bug

#115 `ARCHITECTURE` doc updates
  ARCHITECTURE.md
Labels: documentation

#117 Improves all `/core` files documentation
  lib/core/env.dart
  lib/core/faults/errors/base_error.dart
  lib/core/faults/errors/inconsistent_state_error.dart
  lib/core/faults/errors/serialization_error.dart
  lib/core/faults/exceptions/base_exception.dart
  lib/core/faults/exceptions/url_exception.dart
Labels: documentation

#120 Improves all `/application` files documentation
  lib/application/constants/colors.dart
  lib/application/constants/fonts.dart
  lib/application/constants/images.dart
  lib/application/constants/spacings.dart
  lib/application/constants/strings.dart
  lib/application/coordinator/coordinator_information_parser.dart
  lib/application/coordinator/coordinator_router_delegate.dart
  lib/application/coordinator/routes.dart
  lib/application/coordinator/routes_coordinator.dart
  lib/application/pages/details/collection_details_page.dart
  lib/application/pages/details/details_providers.dart
  lib/application/pages/execution/collection_execution_page.dart
  lib/application/pages/execution/completed_execution_contents.dart
  lib/application/pages/execution/execution_providers.dart
  lib/application/pages/execution/execution_terminal.dart
  lib/application/pages/home/collections/collections_list_view.dart
  lib/application/pages/home/collections/collections_page.dart
  lib/application/pages/home/home_page.dart
  lib/application/pages/home/progress/progress_page.dart
  lib/application/pages/settings/settings_page.dart
  lib/application/pages/splash_page.dart
  lib/application/theme/memo_theme_colors.dart
  lib/application/theme/memo_theme_data.dart
  lib/application/theme/theme_controller.dart
  lib/application/utils/license_update.dart
  lib/application/view-models/app_vm.dart
  lib/application/view-models/execution/collection_execution_vm.dart
  lib/application/view-models/home/collections_vm.dart
  lib/application/view-models/home/progress_vm.dart
  lib/application/view-models/item_metadata.dart
  lib/application/view-models/settings/settings_vm.dart
  lib/application/widgets/animatable_progress.dart
  lib/application/widgets/material/asset_icon_button.dart
  lib/application/widgets/text_tag.dart
  lib/application/widgets/theme/circular_labeled_progress.dart
  lib/application/widgets/theme/collection_card.dart
  lib/application/widgets/theme/hero_collection_card.dart
  lib/application/widgets/theme/secondary_button.dart
  lib/application/widgets/theme/themed_container.dart
  lib/application/widgets/theme/themed_tab_bar.dart
  lib/application/widgets/theme/themed_text_tag.dart
  lib/main.dart
Labels: documentation

#118 Improves all `/data` files documentation
  lib/data/gateways/application_bundle.dart
  lib/data/gateways/database_transaction_handler.dart
  lib/data/gateways/sembast.dart
  lib/data/gateways/sembast_database.dart
  lib/data/repositories/collection_repository.dart
  lib/data/repositories/memo_execution_repository.dart
  lib/data/repositories/memo_repository.dart
  lib/data/repositories/resource_repository.dart
  lib/data/repositories/transaction_handler.dart
  lib/data/repositories/user_repository.dart
  lib/data/repositories/version_repository.dart
  lib/data/serializers/collection_serializer.dart
  lib/data/serializers/memo_serializer.dart
  lib/data/serializers/serializer.dart
  lib/data/serializers/user_serializer.dart
Labels: documentation

#121 Application-wide fixes
  lib/application/app.dart
  lib/application/constants/strings.dart
Labels: bug

#122 Adds `SettingsSection.community` with discord link to `settings_vm`
  lib/application/constants/strings.dart
  lib/application/view-models/settings/settings_vm.dart
Labels: enhancement

#116 Contributors updates
  assets/images/illustrations/2.0x/user_avatar.png
  assets/images/illustrations/3.0x/user_avatar.png
  assets/images/illustrations/user.png
  assets/images/illustrations/user_avatar.png
  lib/application/constants/animations.dart
  lib/application/constants/dimensions.dart
  lib/application/constants/images.dart
  lib/application/constants/strings.dart
  lib/application/pages/details/collection_details_page.dart
  lib/application/pages/details/contributor_view.dart
  lib/application/pages/execution/completed_execution_contents.dart
  lib/application/pages/settings/settings_page.dart
  lib/application/theme/material_theme_data.dart
  lib/application/utils/bottom_sheet.dart
  lib/application/utils/scaffold_messenger.dart
  lib/application/view-models/details/collection_details_vm.dart
  lib/application/widgets/theme/contributors_button.dart
  lib/application/widgets/theme/link.dart
  lib/application/widgets/theme/resources_list.dart
  lib/data/serializers/contributor_serializer.dart
  lib/domain/models/collection.dart
  lib/domain/models/contributor.dart
  lib/domain/transients/collection_memos.dart
  test/data/serializers/collection_memos_serializer_test.dart
  test/data/serializers/collection_serializer_test.dart
  test/data/serializers/contributor_serializer_test.dart
  test/domain/models/collection_test.dart
  test/domain/transients/collection_memos_test.dart
  test/fixtures/contributor.json
  test/fixtures/contributors.json
  test/fixtures/fixtures.dart
Labels: bug, documentation, enhancement

#123 Bumps `CHANGELOG` to `0.1.0-rc.3`
  CHANGELOG.md
  README.md
  README_ptbr.md
Labels: documentation

#124 Bumps both workflows Flutter version to `2.2.3` (latest stable version)
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
Labels: bug, toolkit

#125 Fixes Fastlane tests
  android/fastlane/Fastfile
  ios/fastlane/Fastfile
Labels: bug, toolkit

#127 Adds new collections and its resources
  assets/collections/bdd_fundamentos_01.json
  assets/collections/fundamentos_scrum.json
  assets/collections/guia_scrum.json
  assets/collections/kotlin_fundamentos_01.json
  assets/collections/manifesto_agil.json
  assets/resources.json
Labels: enhancement

#128 Adds `CHANGELOG` for first beta stable release
  CHANGELOG.md
Labels: documentation

#135 Adds a perma discord link - fixes #133
  lib/application/view-models/settings/settings_vm.dart
Labels: bug

#129 Updates Android & iOS release lanes to distribute beta build to external users
  CHANGELOG.md
  android/fastlane/Fastfile
  android/fastlane/metadata/android/pt-BR/changelogs/5.txt
  android/fastlane/metadata/android/pt-BR/changelogs/default.txt
  ios/fastlane/Fastfile
Labels: enhancement, toolkit

#155 Cohesion improvements to the `comecando_com_git` collection - fixes #152
  assets/collections/comecando_com_git.json
Labels: collections

#161 Removes `QuillEditor` cursor
  CHANGELOG.md
  lib/application/pages/execution/execution_terminal.dart
Labels: enhancement, flutter

#165 Worfklows performance improvements
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  android/fastlane/Fastfile
  ios/fastlane/Fastfile
Labels: enhancement, toolkit

#160 Updates `AssetIconButton` default insets padding
  CHANGELOG.md
  lib/application/widgets/material/asset_icon_button.dart
Labels: enhancement, flutter

#157 Adds `starting_git` - `comecando_com_git` english translation
  assets/collections/starting_git.json
Labels: collections

#156 Pull request Workflow Fix
  .github/workflows/pull-request.yml
  ARCHITECTURE.md
  README.md
  README_ptbr.md
  android/app/build.gradle
  ios/.gitignore
  ios/Runner/GoogleService-Info-Template.plist
Labels: bug, toolkit

#134 Update README.md
  README.md
Labels: documentation

#159 Fixes iOS and Android Splash Screens
  android/app/src/main/res/drawable-hdpi/splash.png
  android/app/src/main/res/drawable-mdpi/splash.png
  android/app/src/main/res/drawable-v21/background.png
  android/app/src/main/res/drawable-v21/launch_background.xml
  android/app/src/main/res/drawable-xhdpi/splash.png
  android/app/src/main/res/drawable-xxhdpi/splash.png
  android/app/src/main/res/drawable-xxxhdpi/splash.png
  android/app/src/main/res/drawable/background.png
  android/app/src/main/res/drawable/launch_background.xml
  android/app/src/main/res/values-night/styles.xml
  android/app/src/main/res/values/styles.xml
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Assets.xcassets/Contents.json
  ios/Runner/Base.lproj/LaunchScreen.storyboard
  pubspec.lock
  pubspec.yaml
Labels: enhancement, flutter

#168 Fixes Android debug build
  android/app/build.gradle
Labels: bug, flutter

#170 Removes english localization from iOS project
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/en.lproj/InfoPlist.strings
Labels: bug, flutter

#166 Analytics
  CHANGELOG.md
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/Podfile
  ios/Podfile.lock
  ios/Runner/Info.plist
  pubspec.lock
  pubspec.yaml
Labels: enhancement, flutter

#167 Adds sksl to reduce animations stutter
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  android/app/build.gradle
  android/fastlane/Fastfile
  android_animations.json
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile.lock
  ios/fastlane/Fastfile
  ios_animations.json
  lib/application/pages/details/collection_details_page.dart
  lib/application/pages/details/contributor_view.dart
  lib/application/pages/home/home_page.dart
  lib/application/theme/material_theme_data.dart
  lib/application/utils/bottom_sheet.dart
  lib/application/view-models/app_vm.dart
  lib/application/widgets/theme/circular_labeled_progress.dart
  lib/application/widgets/theme/resources_list.dart
  lib/application/widgets/theme/themed_tab_bar.dart
  lib/data/repositories/collection_repository.dart
  lib/data/repositories/user_repository.dart
  pubspec.lock
  pubspec.yaml
  test/application/widgets/theme/themed_tab_bar_test.dart
Labels: enhancement, flutter
