Repository olmps/memo, pull requests merged in 2021-05, with the labels that each got.

#61 Removes `generated_plugin_registrant.dart` from lint
  analysis_options.yaml
Labels: bug

#78 Adds Fastlane + Github Actions to auto-deploy new releases (#62 clone)
  .github/workflows/flutter-ci.yml
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  ARCHITECTURE.md
  README.md
  README_ptbr.md
  android/.gitignore
  android/Gemfile
  android/app/build.gradle
  android/fastlane/Appfile
  android/fastlane/Fastfile
  android/fastlane/Pluginfile
  ios/.gitignore
  ios/Gemfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  ios/Runner/en.lproj/InfoPlist.strings
  ios/Runner/pt-BR.lproj/InfoPlist.strings
  ios/fastlane/Appfile
  ios/fastlane/Changelog.txt
  ios/fastlane/Fastfile
  ios/fastlane/Matchfile
Labels: feature, toolkit

#85 Updates README (ptBR as well) with new badge and app icon
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  CHANGELOG.md
  README.md
  README_ptbr.md
Labels: bug

#92 Fix release workflow
  .github/workflows/release.yml
  CHANGELOG.md
  android/app/build.gradle
  ios/Runner/Info.plist
Labels: bug, toolkit

#93 Updates collections
  CHANGELOG.md
  assets/collections/comecando_com_git.json
  assets/collections/ecossistema_do_flutter.json
  assets/collections/git_getting_started.json
  assets/collections/swift_fundamentos_01.json
  assets/resources.json
  ios/Podfile.lock
Labels: enhancement

#97 Adds Sprint 5 and 6 (last) docs
  .process/sprints_ptBR/Sprint_5.pdf
  .process/sprints_ptBR/Sprint_6.pdf
Labels: documentation

#98 Improves iOS release workflow performance
  ios/Runner.xcodeproj/project.pbxproj
  ios/exportOptions.plist
  ios/fastlane/Fastfile
Labels: enhancement, toolkit
